#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

for dir in "$HOME/Library/pnpm" "$HOME/.local/share/pnpm"; do
  case ":$PATH:" in *":$dir:"*) ;; *) [ -d "$dir" ] && export PATH="$dir:$PATH" ;; esac
done

pnpm lint-staged
